- hosts: localhost
  become: true
  tasks:
    - include_tasks:
        file: ./tasks/required.yml
        apply:
          tags:
            - required
            - always
      tags:
        - always
    - include_tasks:
        file: ./tasks/debug.yml
        apply:
          tags: debug
      tags:
        - never
    - include_tasks:
        file: ./tasks/general.yml
        apply:
          tags: general
      tags:
        - always
    - include_tasks:
        file: ./tasks/shell.yml
        apply:
          tags:
            - shell
            - terminal
      tags:
        - always
